What is a Python library? Why ^o we use Python libraries?

A Python library is a collection of pre-written code that provides functionalities to perform specific tasks. These libraries contain modules, classes, functions, and methods that can be imported into your Python code, allowing you to access and utilize their capabilities.

Python libraries are used for several reasons:

1. **Code Reusability**: Libraries provide pre-written code that can be reused across different projects, saving time and effort in development.

2. **Efficiency**: By utilizing libraries, developers can leverage optimized and well-tested code, which often leads to more efficient and faster development.

3. **Extended Functionality**: Libraries extend the capabilities of Python by providing additional functionalities that are not available in the core language. For example, libraries like NumPy provide support for numerical computing, while libraries like Matplotlib enable plotting and visualization.

4. **Community Support**: Python has a vibrant and active community that develops and maintains various libraries. These libraries are often open-source and benefit from community contributions, ensuring continuous improvement and updates.

5. **Domain-specific Tasks**: There are libraries available for specific domains such as web development, data analysis, machine learning, natural language processing, etc. These libraries provide tools and utilities tailored to the requirements of those domains, making it easier to work on related tasks.

Overall, Python libraries enhance productivity, facilitate code reuse, and enable developers to efficiently tackle a wide range of tasks across different domains.

2. What is the ^ifference between Numpy array an^ List?

Numpy arrays and lists in Python are both used to store collections of data, but they have some key differences:

1. **Data Types**: Numpy arrays are homogeneous, meaning that all elements in the array must be of the same data type (e.g., integers, floats). This allows for more efficient storage and operations. Lists, on the other hand, can contain elements of different data types.

2. **Memory Efficiency**: Numpy arrays are more memory efficient compared to lists. This is because Numpy arrays store data in a contiguous block of memory, whereas lists store references to objects, which can be scattered across memory.

3. **Performance**: Numpy arrays offer better performance for numerical operations and computations compared to lists. This is due to optimized, compiled C code underlying Numpy operations, whereas lists rely on interpreted Python code.

4. **Functionality**: Numpy arrays offer a wide range of mathematical operations and functions specifically designed for numerical computations (e.g., element-wise operations, linear algebra operations, statistical functions). Lists have a more limited set of operations available by default.

5. **Flexibility**: Lists are more flexible in terms of manipulation and appending elements. Numpy arrays have a fixed size once created, so appending elements can be less efficient as it requires creating a new array with a larger size and copying data over.

Here's a simple example to illustrate the difference:

```python
import numpy as np

# Creating a numpy array
arr_np = np.array([1, 2, 3, 4, 5])

# Creating a list
arr_list = [1, 2, 3, 4, 5]

# Accessing elements
print(arr_np[0])    # Output: 1
print(arr_list[0])  # Output: 1

# Adding elements
arr_np = np.append(arr_np, 6)    # Creates a new array
arr_list.append(6)               # Modifies the original list

# Operations
print(arr_np * 2)    # Output: [ 2  4  6  8 10 12]
print(arr_list * 2)  # Output: [1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]

# Mathematical operations
print(np.sum(arr_np))    # Output: 21
print(sum(arr_list))     # Output: 21
```

In summary, Numpy arrays are better suited for numerical computations and large datasets due to their efficiency and specialized functionality, while lists offer more flexibility for general-purpose data storage and manipulation.

3. Fin^ the shape, size an^ ^imension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [5]:

import numpy as np

# Define the array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Shape of the array
shape = arr.shape

# Size of the array (total number of elements)
size = arr.size

# Dimension of the array
dimension = arr.ndim

print("Shape of the array:", shape)  # Output: (3, 4)
print("Size of the array:", size)    # Output: 12
print("Dimension of the array:", dimension)  # Output: 2




Shape of the array: (3, 4)
Size of the array: 12
Dimension of the array: 2


4. Write python co^e to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [6]:
import numpy as np

# Define the array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Access the first row
first_row = arr[0]

print("First row of the array:", first_row)


First row of the array: [1 2 3 4]


5. How ^o you access the element at the thir^ row an^ fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [7]:
import numpy as np

# Define the array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Access the element at the third row and fourth column
element = arr[2, 3]

print("Element at the third row and fourth column:", element)



Element at the third row and fourth column: 12


6. Write co^e to extract all o^^-in^exe^ elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [8]:
import numpy as np

# Define the array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Extract all odd-indexed elements
odd_indexed_elements = arr[:, 1::2]

print("Odd-indexed elements of the array:")
print(odd_indexed_elements)


Odd-indexed elements of the array:
[[ 2  4]
 [ 6  8]
 [10 12]]


7. How can you generate a ran^om 3x3 matrix with values between 0 an^ 1?

In [9]:
import numpy as np

# Generate a random 3x3 matrix with values between 0 and 1
random_matrix = np.random.rand(3, 3)

print("Random 3x3 matrix with values between 0 and 1:")
print(random_matrix)


Random 3x3 matrix with values between 0 and 1:
[[0.87830896 0.2650029  0.57356066]
 [0.79428616 0.35113058 0.51904867]
 [0.50991557 0.68403762 0.29137776]]


8. Describe the ^ifference between np.ran^om.ran^ an^ np.ran^om.ran^n?

The functions `np.random.rand` and `np.random.randn` are both used to generate random numbers in NumPy, but they differ in how they generate those numbers and the distributions they sample from:

1. **np.random.rand**:
   - This function generates random numbers from a uniform distribution over the interval [0, 1).
   - It takes as input the dimensions of the array you want to create.
   - Each element in the resulting array is sampled independently from a uniform distribution between 0 and 1.
   - The function `np.random.rand` is suitable when you need random numbers with equal probability over a specified range, such as for generating random matrices for testing purposes or initializing weights in machine learning models.

2. **np.random.randn**:
   - This function generates random numbers from a standard normal distribution (mean 0 and standard deviation 1).
   - It takes as input the dimensions of the array you want to create.
   - Each element in the resulting array is sampled independently from a standard normal distribution (Gaussian distribution) with mean 0 and standard deviation 1.
   - The function `np.random.randn` is commonly used when you need random numbers that follow a normal distribution, which is often the case in statistical analysis, modeling, and simulation tasks.

Here's a simple example demonstrating the difference between the two functions:

```python
import numpy as np

# Generate a 2x2 array with random values from a uniform distribution [0, 1)
array_uniform = np.random.rand(2, 2)

# Generate a 2x2 array with random values from a standard normal distribution
array_normal = np.random.randn(2, 2)

print("Array from np.random.rand:")
print(array_uniform)

print("\nArray from np.random.randn:")
print(array_normal)
```

Output (example):
```
Array from np.random.rand:
[[0.48077659 0.48587132]
 [0.51032114 0.27500266]]

Array from np.random.randn:
[[ 0.31620737 -1.43779147]
 [-1.48263332 -0.54029664]]
```

In summary, `np.random.rand` generates random numbers from a uniform distribution [0, 1), while `np.random.randn` generates random numbers from a standard normal distribution with mean 0 and standard deviation 1.

9. Write co^e to increase the ^imension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [10]:
import numpy as np

# Define the array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Increase the dimension of the array
new_arr = arr[:, :, np.newaxis]

print("Original array:")
print(arr)

print("\nArray with increased dimension:")
print(new_arr)

print("\nShape of the original array:", arr.shape)
print("Shape of the array with increased dimension:", new_arr.shape)


Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Array with increased dimension:
[[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]]

Shape of the original array: (3, 4)
Shape of the array with increased dimension: (3, 4, 1)


10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [11]:
import numpy as np

# Define the array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Transpose the array
transposed_arr = np.transpose(arr)

print("Transposed array:")
print(transposed_arr)


Transposed array:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


11. Consi^er the following matrix:
Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

In [14]:
import numpy as np

# Define matrices A2 and B2
A2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

B2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

# 1. Index-wise multiplication
index_wise_multiplication = A2 * B2

# 2. Matrix multiplication
matrix_multiplication = np.dot(A2, B2.T)  # or A2 @ B2.T

# 3. Add both the matrices
addition = A2 + B2

# 4. Subtract matrix B from matrix A
subtraction = A2 - B2

# 5. Divide matrix B by matrix A (element-wise)
division = B2 / A2

# Display results
print("1. Index-wise multiplication:\n", index_wise_multiplication)
print("\n2. Matrix multiplication:\n", matrix_multiplication)
print("\n3. Addition:\n", addition)
print("\n4. Subtraction:\n", subtraction)
print("\n5. Division (element-wise):\n", division)



1. Index-wise multiplication:
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]

2. Matrix multiplication:
 [[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]

3. Addition:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

4. Subtraction:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

5. Division (element-wise):
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


12. Which function in Numpy can be use^ to swap the byte or^er of an array?

In [15]:
import numpy as np

# Define an array
arr = np.array([1, 2, 3, 4], dtype=np.int32)

# Swap the byte order of the array
swapped_arr = arr.byteswap()

print("Original array:", arr)
print("Swapped array:", swapped_arr)


Original array: [1 2 3 4]
Swapped array: [16777216 33554432 50331648 67108864]


13. What is the significance of the np.linalg.inv function?

The `np.linalg.inv` function in NumPy is used to compute the inverse of a square matrix. In linear algebra, the inverse of a matrix is a matrix that, when multiplied by the original matrix, results in the identity matrix.

The significance of the `np.linalg.inv` function lies in its utility in various mathematical and scientific applications, particularly in solving systems of linear equations, computing determinants, and performing other matrix operations. Here are some key points regarding its significance:

1. **Solving systems of linear equations**: In many mathematical and scientific problems, systems of linear equations arise. The inverse of a matrix can be used to solve such systems, as multiplying both sides of the equation by the inverse matrix allows for direct computation of the solution.

2. **Computing determinants**: The determinant of a matrix is a scalar value that provides important information about the matrix, such as whether it is singular (non-invertible) or non-singular (invertible). The determinant of a matrix can be computed using the `np.linalg.det` function, and the inverse of a matrix can be used to compute the determinant efficiently.

3. **Solving least squares problems**: In regression analysis and optimization problems, the inverse of a matrix is often used to compute least squares solutions efficiently.

4. **Numerical stability**: The `np.linalg.inv` function in NumPy provides a stable and efficient implementation for computing the inverse of a matrix, even for large matrices. It utilizes optimized algorithms and numerical techniques to ensure accuracy and efficiency in computations.

5. **Inverse as a tool for matrix operations**: The inverse of a matrix is a fundamental tool in various matrix operations, such as matrix multiplication, division, and solving linear systems. It allows for the representation of solutions to linear equations in a compact form and enables the manipulation and analysis of matrices in mathematical and scientific computations.

Overall, the `np.linalg.inv` function plays a crucial role in linear algebra and numerical computing, providing a convenient and efficient way to compute the inverse of matrices and enabling a wide range of mathematical and scientific applications.

14. What ^oes the np.reshape function ^o, an^ how is it use^?

The np.reshape function in NumPy is used to change the shape of an array without changing its data. It allows you to reorganize the elements of an array into a new shape, provided that the total number of elements remains the same.
#syntex
np.reshape(array, new_shape, order='C')


15. What is broa^casting in Numpy?

Broadcasting in NumPy is a powerful mechanism that allows arrays with different shapes to be combined in arithmetic and other operations. Broadcasting essentially extends the concept of element-wise operations to arrays with different shapes, enabling NumPy to perform operations even when the shapes of the arrays do not match exactly.
Here are the key rules of broadcasting in NumPy:

If the arrays have a different number of dimensions, the shape of the array with fewer dimensions is padded with ones on its leading (left) side.

If the shape of the arrays does not match in any dimension, and neither of them is equal to 1, NumPy raises a ValueError.

After applying the above rules, the sizes of the arrays must match in each dimension or one of them must be 1.


In [17]:
#example 
import numpy as np

# Define two arrays with different shapes
arr1 = np.array([1, 2, 3])
arr2 = np.array([[4],
                 [5],
                 [6]])

# Perform element-wise addition using broadcasting
result = arr1 + arr2

print("Array 1:")
print(arr1)
print("\nArray 2:")
print(arr2)
print("\nResult after broadcasting:")
print(result)


Array 1:
[1 2 3]

Array 2:
[[4]
 [5]
 [6]]

Result after broadcasting:
[[5 6 7]
 [6 7 8]
 [7 8 9]]
